baseURL       = "https://barbaraliz.netlify.app/"
languageCode  = "fr-FR"
title         = "Barbara Lizama | Developement web"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = "accueil"
    weight  = 1
  [[menu.nav]]
    name    = "A propos"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/simbole.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    heading               = ""
    tagline               = ""
    primary_button        = "Mon travail"
    primary_button_url    = "Contacte"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    background_image    = "/images/bliz_back.png"
    title     = "PROJETS"
    subtitle  = "Apprendre en faisant"

  [params.call_to_action]
    enable              = true
    background_image    = "/images/pattern_transp.png"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Contact"
    primary_button_url  = "contact"
    secondary_button    = "Pas convaincu"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Boulevard de l'Yser, Rouen"
      phone   = "07 49 49 40 31"
      email   = "libarbara.dev@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/Barbaralz"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/barb.couleur"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"